# Site settings
title: Formal Friday Blog
description: > #
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://formalfriday.club" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username: codebeer

# Build settings
markdown: kramdown

exclude: [exclude]

# Custom Stuff
emails:
  - brad@bradleycurran.com
  - hi@mattwitherow.com
