# Site settings
title: codebeer
description: > #
  Why is this called codebeer you may ask?<br/>
  Well, we code and we like beer. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codebeer.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  codebeer

# Build settings
markdown: kramdown

exclude: [exclude]

# Custom Stuff
emails:
  - brad@bradleycurran.com
